<center>
    
# **working with data in Python**

</center>

In [51]:
file1 = open("./example1.txt", "r")
file1

In [52]:
file1.name

'./example1.txt'

In [53]:
file1.mode

'r'

In [54]:
file1.closed

False

In [55]:
file1.read()

'hello line1\nhello line2'

In [56]:
file1.close()

In [57]:
file1.read()

ValueError: I/O operation on closed file.

In [58]:
#To simplify file handling and ensure proper closure of files, 
#Python provides the "with" statement. 
#It automatically closes the file when operations 
#within the indented block are completed. 
#This is considered best practice when working with files.

with open("example1.txt", "r") as file:
    file_stuff = file.read()
print(file_stuff)

hello line1
hello line2

In [59]:
!pip install requests pandas

Requirement already satisfied: requests in C:\Users\rizwa\AppData\Local\Programs\Python\Python313\Lib\site-packages (2.34.2)
Requirement already satisfied: pandas in C:\Users\rizwa\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\rizwa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\rizwa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\rizwa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\rizwa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from requests) (2026.2.25)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\rizwa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\rizwa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\rizwa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\rizwa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [72]:
import requests

filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0101EN-SkillsNetwork/labs/Module%204/data/example1.txt"


def download(url, save_as):
    # Fetch the file over standard HTTP
    response = requests.get(url)

    # Check if the download was successful (Status code 200)
    if response.status_code == 200:
        with open(save_as, "wb") as f:
            f.write(response.content)
        print("done")
    else:
        print(f"Failed to download. Status code: {response.status_code}")


# Run the function
download(filename, "example2.txt")

done

In [63]:
# Read certain amount of characters

with open("example1.txt", "r") as file1:
    print(file1.read(4))
    print(file1.read(4))
    print(file1.read(7))
    print(file1.read(15))

hell
o li
ne1
hel
lo line2

In [66]:
# Create a new file Example2.txt for writing
with open('Example20.txt', 'w') as file20:
    file20.write("This is line A\n")
    file20.write("This is line B\n")
    # file1 is automatically closed when the 'with' block exits

In [67]:
# List of lines to write to the file
Lines = ["This is line 1", "This is line 2", "This is line 3"]

# Create a new file Example3.txt for writing
with open('Example30.txt', 'w') as file30:
    for line in Lines:
        file30.write(line + "\n")
    # file2 is automatically closed when the 'with' block exits

In [69]:
# Data to append to the existing file
new_data = "This is line C"

# Open an existing file Example2.txt for appending
with open('Example30.txt', 'a') as file30:
    file30.write(new_data + "\n")
    # file1 is automatically closed when the 'with' block exits

# Pandas: 
* Pandas is a popular open-source data manipulation and analysis library for the Python programming language
* It has functions for analyzing, cleaning, exploring, and manipulating data

Key features and functionalities of Pandas
Data Structures: Pandas offers two primary data structures - DataFrame and Series.

A DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).

A Series is a one-dimensional labeled array, essentially a single column or row of data.

In [70]:
import pandas as pd

# DataFrame

In [76]:
csv_path = "example1.csv"
df = pd.read_csv(csv_path) # df -> datafrome
df

      Name  Age           City
0    Alice   30       New York
1      Bob   25  San Francisco
2  Charlie   35        Chicago

In [77]:
df['Name']

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: str

In [79]:
df[df['Age'] > 30]

      Name  Age     City
2  Charlie   35  Chicago

In [81]:
# Creating a DataFrame from a dictionary
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 28],
        'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']}

df = pd.DataFrame(data)
df

      Name  Age           City
0    Alice   25       New York
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles
3    David   28        Chicago

In [83]:
df.iloc[2] # Access the third row by position

Name        Charlie
Age              35
City    Los Angeles
Name: 2, dtype: object

In [84]:
print(df.loc[1])    # Access the second row by label

Name              Bob
Age                30
City    San Francisco
Name: 1, dtype: object

In [85]:
df[1:3] # Select specific rows

      Name  Age           City
1      Bob   30  San Francisco
2  Charlie   35    Los Angeles

In [87]:
unique_dates = df['Age'].unique()
unique_dates

array([25, 30, 35, 28])

In [100]:
df.to_csv('trading_data.csv', index=False)

In [102]:
import requests

filename = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv"

def download(url, save_as):
    # Fetch the file over standard HTTP
    response = requests.get(url)

    # Check if the download was successful (Status code 200)
    if response.status_code == 200:
        with open(save_as, "wb") as f:
            f.write(response.content)
        print("done")
    else:
        print(f"Failed to download. Status code: {response.status_code}")


# Run the function
download(filename, "Product-sales.csv")
df = pd.read_csv("Product-sales.csv")
df

done

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami

In [104]:
df[['Quantity']]

   Quantity
0         2
1         3
2         5
3        10
4         1

In [105]:
df['Product']

0        Laptop
1    Smartphone
2    Desk Chair
3      Notebook
4       Monitor
Name: Product, dtype: str

In [106]:
df.iloc[0,0]

np.int64(1)

In [109]:
df.iloc[2:6,5]

2    750
3     20
4    300
Name: Total, dtype: int64

# Series

In [91]:
# Create a Series from a list
data = [10, 20, 30, 40, 50]
s = pd.Series(data)
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [97]:
s[2]     # Access the element with label 2 (value 30)

np.int64(30)

In [98]:
s.iloc[3] # Access the element at position 3 (value 40)

np.int64(40)

In [99]:
s[1:4]  # Access a range of elements by label

1    20
2    30
3    40
dtype: int64